/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class intelligence_Maddpg_Models */

#ifndef _Included_intelligence_Maddpg_Models
#define _Included_intelligence_Maddpg_Models
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     intelligence_Maddpg_Models
 * Method:    sayHello
 * Signature: ([[F)V
 */
JNIEXPORT void JNICALL Java_intelligence_Maddpg_Models_sayHello
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     intelligence_Maddpg_Models
 * Method:    initNetworks
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_intelligence_Maddpg_Models_initNetworks
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
